server:
  port: 8080
  tomcat:
    accept-count: 1000
    max-threads: 800
    min-spare-threads: 100
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.159.3:3306/ywb?rewriteBatchedStatements=true&autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=Asia/Shanghai
  redis:
    database: 0
    host: 192.168.159.3
    port: 6379
#    password:
    jedis:
      pool:
        max-active: 200

# Redis数据库索引（默认为0）
#spring.redis.database=0
## Redis服务器地址
#spring.redis.host=192.168.159.3
## Redis服务器连接端口
#spring.redis.port=6379
## Redis服务器连接密码（默认为空）
#spring.redis.password=
## 连接池最大连接数（使用负值表示没有限制）
#spring.redis.jedis.pool.max-active=200
# 连接池最大阻塞等待时间（使用负值表示没有限制）
# spring.redis.jedis.pool.max-wait=-1
# 连接池中的最大空闲连接
# spring.redis.jedis.pool.max-idle=10
# 连接池中的最小空闲连接
# spring.redis.jedis.pool.min-idle=0
# 连接超时时间（毫秒）
# spring.redis.timeout=3000


#mybatis:
#  mapper-locations: classpath:mapper/**/*.xml


mybatis-plus:
#  configuration:
#    map-underscore-to-camel-case: true
#    auto-mapping-behavior: full
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/**/*.xml


